<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="LoginTest"
           tests="1"
           failures="1"
           errors="0"
           skipped="0"
           time="27.010">
  <properties />
            <testcase name="loginSuccess" time="27.010" classname="com.witontek.ehospital2.test.LoginTest">
                <failure type="java.lang.AssertionError"
                  message="故意断言失败，并中断执行此用例 expected [2] but found [1]"
              >
<![CDATA[java.lang.AssertionError: 故意断言失败，并中断执行此用例 expected [2] but found [1]
  org.testng.Assert.fail(Assert.java:93)
  org.testng.Assert.failNotEquals(Assert.java:512)
  org.testng.Assert.assertEqualsImpl(Assert.java:134)
  org.testng.Assert.assertEquals(Assert.java:115)
  org.testng.Assert.assertEquals(Assert.java:388)
  com.witontek.ehospital2.base.Log.errorShot(Log.java:49)
  com.witontek.ehospital2.base.WebElementsUtils.getElement(WebElementsUtils.java:32)
  com.witontek.ehospital2.base.WebElementsUtils$1.apply(WebElementsUtils.java:61)
  com.witontek.ehospital2.base.WebElementsUtils$1.apply(WebElementsUtils.java:1)
  org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:209)
  com.witontek.ehospital2.base.WebElementsUtils.findElement(WebElementsUtils.java:58)
  com.witontek.ehospital2.base.WebElementsUtils.getText(WebElementsUtils.java:121)
  com.witontek.ehospital2.page.MainPage.getUserName(MainPage.java:93)
  com.witontek.ehospital2.test.LoginTest.loginSuccess(LoginTest.java:30)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:744)
  org.testng.TestRunner.run(TestRunner.java:602)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
  org.testng.SuiteRunner.run(SuiteRunner.java:289)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
  org.testng.TestNG.runSuites(TestNG.java:1144)
  org.testng.TestNG.run(TestNG.java:1115)
  org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
      </failure>

          </testcase>
  
  
  
</testsuite>
